version: "2.3"
services:
  nginx:
    image: docker-compose-nginx
    ports:
      - "80:80"
    depends_on:
      php:
        condition: service_healthy
    environment:
      - ENV=production
  php:
    image: docker-compose-php
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
